project:
  type: website
  output-dir: docs

website:
  title: "2025 창의연합과제연구"
  navbar:
    left:
      - href: project 1 250724.ipynb
        text: Project1
      - href: project2.ipynb
        text: Project2
      - href: project3.ipynb
        text: Project3

format:
  html:
    theme:
      - minty
      - brand
    css: styles.css
    toc: true



